export default {
  register: require("../assets/images/register.png"),
  google: require("../assets/images/Google.png"),
  tick: require("../assets/images/tick.png"),
  help: require("../assets/images/help.png"),
  kyc: require("../assets/images/kyc.png"),
  blueChip: require("../assets/images/bluechip.png"),
  stableFund: require("../assets/images/stablefund.png"),
  setupIcon: require("../assets/images/setupIcon.png"),
  rightIcon: require("../assets/images/rightArrow.png"),
  headset: require("../assets/images/headset.png"),
  lock: require("../assets/images/lock.png"),
  upiIcon: require("../assets/images/upi.png"),
  arrowLeft: require("../assets/images/arrow-left.png"),
};
